name = "billing-app"
type = "javascript"

account_id = "damp-lab-0028"
workers_dev = true
compatibility_date = "2024-09-15"

[triggers]
crons = ["0 0 * * *"]

[build]
command = "npm install && npm run build"

[env.production]
workers_dev = false
compatibility_date = "2024-09-15"
